baseURL = "/"
languageCode = "en-us"
relativeURls = "true"
summaryLength = "10"
theme = "kross-hugo"
title = "saltï"
[menu]
main = []
[params]
address = ""
author = "Leo M. Davis"
copyright = "Copyrighht &copy; 2022 |  [justsoantsy.com](https://justsoantsy.com)"
description = "This is meta description"
email = "info@justsoantsy.com"
google_analitycs_id = "Your ID"
home = "salti.eth"
logo = "/images/justsoantsy-2021-logo-white.png"
phone = ""
social = []
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
